#!/bin/sh
#
# Installs these scripts into accessible locations

if [ `id -u` -eq 0 ]
then
  cp bin/* /usr/local/bin
else
  mkdir -p ~/bin
  cp bin/* ~/bin

  CI_BUILD=`which gitlab-ci-build`
  if [ -z "$CI_BUILD" ]
  then
    echo "ERROR. Installed scripts into ~/bin, but ~/bin is not in your PATH"
  fi
fi

